<?php

namespace app\models;

use app\common\exceptions\NotImplementedException;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\web\IdentityInterface;

/**
 * Class User
 * @package app\models
 * 
 * @property int $id
 * @property string $username
 * @property string $email
 * @property string $password
 * @property string $authKey
 * @property \DateTime $created_at
 * @property \DateTime $updated_at
 *
 */
class User extends ActiveRecordExtended implements IdentityInterface
{
    
    const SCENARIO_UPDATE = 'update';
    
    public static function tableName()
    {
        return 'cp_users';
    }

    public function getCpRights()
    {
        return $this->hasOne(UserCpRights::className(), ['user_id' => 'id']);
    }

    public function getBoardRights()
    {
        return $this->hasOne(UserBoardRights::className(), ['user_id' => 'id']);
    }

    public function getChatRights()
    {
        return $this->hasOne(UserChatRights::className(), ['user_id' => 'id']);
    }

    /**
     * @return null|User
     */
    public static function getUserBySession()
    {
        $username = \yii::$app->session->get('username');
        return $user = static::find()->where('username = :username', [':username' => $username])->one();
    }
    
    public function checkRights()
    {
        return false;
    }
    
    public function rules()
    {
        return [
            [['username', 'password'], 'required'],
            ['username', 'unique'],
            ['username', 'string', 'length' => [1, 255]],
            
            ['password', 'string', 'length' => [1, 255]],
            
//            Должен валидироваться, но в данный момент new_password - safe аттрибут
//            ['new_password', 'required'/*, 'on' => self::SCENARIO_UPDATE*/],
//            ['new_password', 'string', 'length' => [1, 255]],

            ['email', 'required'],
            ['email', 'unique'],
            ['email', 'email']
        ];
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ]
        ];
    }

    public function scenarios()
	{
        $scenarios = parent::scenarios();
        $scenarios['default'] = ['username', 'password', 'email'];
        $scenarios[self::SCENARIO_UPDATE] = ['username','password', 'new_password', 'email'];
        return $scenarios;
    }

    /**
     * @param int|string $id
     * @return null|User
     */
    public static function findIdentity($id)
    {
        return User::findOne($id);
    }

    /**
     * @param mixed $token
     * @param null $type
     * @throws NotImplementedException
     * @return void
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotImplementedException();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getAuthKey()
    {
        return $this->authKey;
    }

    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}